version: '2'
services:
  redis:
    image: redis:5.0.3-alpine
    volumes:
    - "redis:/redis_data"
  bot:
    build: .
    volumes:
      - ./data:/usr/src/app/data
      - ./matrosskin:/usr/src/app/matrosskin
    env_file:
      - .env
    environment:
      - redis_host=redis
      - PYTHONPATH=/usr/src/app
      - LC_ALL=ru_RU.UTF-8
    depends_on:
      - redis

volumes:
  redis: {}
